# FAQs

If you believe any of the information presented below is incorrect, please [contact us here](mailto:40885423.beisgov.onmicrosoft.com@emea.teams.ms) 

### Q: How can I book an external or Civil Service Learning Course?
**A:** See our document on how to book an external course: [GORS Guide to booking an external courses](https://github.com/GORSlearningdevelopmentpages/GORSlearningdevelopmentpages.github.io/raw/master/docs/files/GORS%20Guide%20to%20booking%20an%20external%20course%20v2.0.pptx) (Powerpoint, 106KB)

### Q: How much L&D time am I entitled to?
**A:** There are a few important numbers to keep in mind.

* As a civil servant, you're entitled to **5 days** of dedicated "learning and development" per year.
* As a badged GORS analyst, you're expected to undertake a minimum of **100 hours** of CPD per year (pro-rata for part-time staff) which should be logged in a CPD log. At least half of this should be OR focused.
* A general rule of thumb is that L&D should take on average **5-10%** of your time each week, or somewhere between a few hours and a half day if you work full time.

Don't forget that learning on the job also counts as development (and can be included towards the required 100 hours for GORS).

### Q: How should I log my 100 hours of CPD for GORS?
**A:** The following guide and log template (see annex of linked guide) is endorsed by GORS CMU: [GORS CPD Log](http://www.operational-research.gov.uk/members/library/download/846/){target="_blank"}.
 
To note, from April 2020 it will become mandatory for the CPD log to be signed off by another OR.

### Q: How should I decide what L&D to undertake?
**A:** Speak to your line manager or mentor about your development needs in the first instance. You can also use the [Analysis Function online skills tool](mailto:analysis.function@ons.gov.uk) to help identify gaps in your L&D and suggested courses. If you'd like to browse what else is available, have a look at our [L&D Library](library.html).

### Q: What can I do to make time for L&D?
**A:** Some people find it helpful to schedule a certain time each week or fortnight to dedicate to L&D activities. It can be helpful to speak with your line manager about this if you're concerned about getting pulled into other work during this time -- it may be possible for you to agree a "quiet" period each week where you ignore incoming emails and focus solely on L&D. At times business need may mean you can't spend the same amount of time on L&D, though this should average out over a year.

### Q: I'm struggling to get enough L&D time, what should I do?
**A:** If you feel you're not getting enough time to do the development you need, speak to your line manager. Development should be a key part of everyone's monthly performance discussions with their manager. You're also welcome to discuss this with your head of profession or deputy head of profession as all badged GORS members are expected to take on a certain amount of CPD each year.

### Q: What counts as OR CPD?
**A:** CPD activities should be focused on learning something new and relevant. It is sometimes helpful to refresh old knowledge, but the focus is on providing new insights, competencies, behaviours or learning. It is always the outcome of the learning rather than the method that matters. Any activity can count as CPD so long as something new and relevant has been learnt.

Some examples of relevant CPD activity may include:

* On-the-job learning,
* Online courses,
* Desk based learning,
* Formal qualifications,
* Short training courses,
* Conferences,
* Seminars (for example Coffee & Coding),
* Reading,
* Secondments,
* Involvement in collaborative GORS initiatives,
* The acquisition of new OR/data science skills,
* Articles written to publications,
* Specific work experience or project aimed at developing a new skill, or
* Teaching and coaching.

---

::: {.small-para}
This site was built using [govdown](https://ukgovdatascience.github.io/govdown/){target="_blank"}.
:::
