# Welcome to the GORS L&D Pages!

::: {.lead-para}
This site aims to be a one-stop shop for all learning & development resources pertaining to Operational Research within the Government Operational Research Service (GORS).
:::

It's tough being an operational researcher, there's so much you need to learn, but it isn't always easy to acquire that knowledge when needed. Resources are quite sparse and not always easily obtainable, this resource aims to fix that. Here you will find links to resources that we think will be useful to you as an operational researcher in the civil service. This site is split into two sections, the L&D Library and FAQs:

## L&D Library
Our [L&D Library](library.html) is a database of curated courses that cover various topics which fall under the remit of a typical operational researcher, this page also includes ratings & reviews shared by our fellow operational researchers. The L&D Library covers:

1. General Analytical Skills
2. Programming/Data Science
3. Hard OR
4. Soft OR
5. General Professional Skills
6. OR Society
7. Other GORS Resources

## FAQs
Our [FAQs](faq.html) page answers some of those niggling questions you may have about GORS and it's L&D approach. The FAQs section covers:

1. Booking External Courses
2. L&D Commitments
3. CPD Log

<br>

::: {.warning}
If you have any suggestions for these pages, questions about L&D, would like to run an internal course for GORS members, or would like to get involved with our group please get in touch with us: [SET UP EMAIL]()
:::


---

::: {.small-para}
This site was built using [govdown](https://ukgovdatascience.github.io/govdown/).
:::
